# Generated from src/lettermint/_async/__init__.py by scripts/unasync.py — do not edit.
"""The synchronous client, generated by ``scripts/unasync.py``."""

from .client import Lettermint
from .emails import EmailBuilder, Emails
from .resources import (
    Domains,
    Messages,
    Projects,
    ReportForwarding,
    Resource,
    Routes,
    Stats,
    Suppressions,
    Team,
    TeamMembers,
    WebhookDeliveries,
    Webhooks,
)

__all__ = [
    "Domains",
    "EmailBuilder",
    "Emails",
    "Lettermint",
    "Messages",
    "Projects",
    "ReportForwarding",
    "Resource",
    "Routes",
    "Stats",
    "Suppressions",
    "Team",
    "TeamMembers",
    "WebhookDeliveries",
    "Webhooks",
]
