#!/usr/bin/env python3
"""Regenerate or check ``src/lettermint/_generated`` with the Lettermint SDK generator.

The generator (``lettermint/sdk-generator``) is private. Point
``LETTERMINT_SDK_GENERATOR`` at a checkout, or keep one at ``../sdk-generator``.
The pinned specs come from GitHub (``gh api``), or from a local monorepo
checkout named by ``LETTERMINT_MONOREPO``. The generator needs Python 3.11+;
``LETTERMINT_SDK_GENERATOR_PYTHON`` names the interpreter (default: this one).

    python scripts/generate.py          # regenerate from the generator's spec.next.lock.json
    python scripts/generate.py --check  # fail when the files differ from the generator's output

Without a generator checkout, as in CI, ``--check`` only verifies the headers:
every generated file must start with the same generator header (spec commit,
both spec hashes, the ``next`` naming profile).
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "lettermint" / "_generated"
FILES = ("__init__.py", "types.py", "operations.py")
HEADER = [
    re.compile(r"# Generated by lettermint/sdk-generator — do not edit\.$"),
    re.compile(r"# Spec: lettermint/lettermint@[0-9a-f]{40}( \(.+\))?$"),
    re.compile(r"# sending-openapi\.json SHA-256: [0-9a-f]{64}$"),
    re.compile(r"# team-openapi\.json SHA-256: [0-9a-f]{64}$"),
    re.compile(r"# Naming profile: next$"),
]


def generator() -> Path | None:
    configured = os.environ.get("LETTERMINT_SDK_GENERATOR")
    path = Path(configured) if configured else ROOT.parent / "sdk-generator"
    return path if (path / "lettermint_sdkgen").is_dir() else None


def check_headers() -> int:
    headers = set()
    for name in FILES:
        path = OUT / name
        if not path.exists():
            print(f"missing: {path}", file=sys.stderr)
            return 1
        lines = path.read_text().splitlines()[: len(HEADER)]
        if len(lines) < len(HEADER) or not all(
            p.match(line) for p, line in zip(HEADER, lines, strict=True)
        ):
            print(f"{path} has no generator header; regenerate it", file=sys.stderr)
            return 1
        headers.add("\n".join(lines))
    if len(headers) != 1:
        print(
            "the generated files come from different generator runs; regenerate them",
            file=sys.stderr,
        )
        return 1
    print("generated headers ok:\n" + headers.pop())
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    parser.add_argument("--check", action="store_true", help="do not write; verify the files")
    args = parser.parse_args(argv)
    checkout = generator()
    if checkout is None:
        if not args.check:
            print(
                "No SDK generator found: set LETTERMINT_SDK_GENERATOR or check it out at ../sdk-generator",
                file=sys.stderr,
            )
            return 2
        print("No SDK generator checkout; checking the generated headers only.")
        return check_headers()
    lock = checkout / "spec.next.lock.json"
    command = [
        os.environ.get("LETTERMINT_SDK_GENERATOR_PYTHON", sys.executable),
        "-m",
        "lettermint_sdkgen",
    ]
    monorepo = os.environ.get("LETTERMINT_MONOREPO")
    fetch = [*command, "fetch-specs", "--lock", str(lock)] + (
        ["--monorepo", monorepo] if monorepo else []
    )
    fetched = subprocess.run(fetch, cwd=checkout)
    if fetched.returncode != 0:
        return fetched.returncode
    emit = [*command, "emit", "python", "--profile", "next", "--lock", str(lock), "--out", str(OUT)]
    result = subprocess.run(emit + (["--check"] if args.check else []), cwd=checkout)
    if result.returncode != 0:
        return result.returncode
    return check_headers()


if __name__ == "__main__":
    sys.exit(main())
