#!/usr/bin/env python3
"""Generate the synchronous client (``lettermint._sync``) from the asynchronous one.

The SDK has one hand-written implementation of the client, the sub-clients
and the email builder: ``src/lettermint/_async``. This script rewrites it
token by token into ``src/lettermint/_sync``: ``async def`` becomes ``def``,
``await`` disappears, ``AsyncFoo`` becomes ``Foo``, ``AsyncIterator`` becomes
``Iterator``, ``__aenter__`` becomes ``__enter__``, and so on. Everything
that differs for real between the two (sending requests, the deadline) lives
in ``_transport.py``, which is written by hand for both.

    python scripts/unasync.py          # rewrite src/lettermint/_sync
    python scripts/unasync.py --check  # fail when src/lettermint/_sync is stale
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "lettermint" / "_async"
TARGET = ROOT / "src" / "lettermint" / "_sync"

RULES: list[tuple[re.Pattern[str], str]] = [
    (re.compile(pattern), replacement)
    for pattern, replacement in (
        (
            r"The asynchronous client\. ``scripts/unasync\.py`` generates ``lettermint\._sync`` from it\.",
            "The synchronous client, generated by ``scripts/unasync.py``.",
        ),
        (r"\basync def\b", "def"),
        (r"\basync for\b", "for"),
        (r"\basync with\b", "with"),
        (r"\bawait ", ""),
        (r"\b__aenter__\b", "__enter__"),
        (r"\b__aexit__\b", "__exit__"),
        (r"\baclose\b", "close"),
        (r"\bAsync([A-Z]\w*)", r"\1"),
        (r"\b_async\b", "_sync"),
        (r"\basynchronous\b", "synchronous"),
    )
]


def header(name: str) -> str:
    return f"# Generated from src/lettermint/_async/{name} by scripts/unasync.py — do not edit.\n"


def convert(text: str) -> str:
    lines = []
    for line in text.splitlines(keepends=True):
        for pattern, replacement in RULES:
            line = pattern.sub(replacement, line)
        lines.append(line)
    return "".join(lines)


def outputs() -> dict[Path, str]:
    return {
        TARGET / path.name: header(path.name) + convert(path.read_text())
        for path in sorted(SOURCE.glob("*.py"))
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    parser.add_argument(
        "--check", action="store_true", help="do not write; fail when the files differ"
    )
    args = parser.parse_args(argv)
    files = outputs()
    stale = sorted(
        {path for path, text in files.items() if not path.exists() or path.read_text() != text}
        | {path for path in TARGET.glob("*.py") if path not in files}
    )
    if args.check:
        for path in stale:
            current = path.read_text().splitlines() if path.exists() else []
            wanted = files.get(path, "").splitlines()
            diff = difflib.unified_diff(
                current, wanted, f"{path} (committed)", f"{path} (generated)", lineterm="", n=1
            )
            print("\n".join(list(diff)[:40]), file=sys.stderr)
        if stale:
            print("src/lettermint/_sync is stale; run python scripts/unasync.py", file=sys.stderr)
            return 1
        print("src/lettermint/_sync is up to date")
        return 0
    TARGET.mkdir(exist_ok=True)
    for path in TARGET.glob("*.py"):
        if path not in files:
            path.unlink()
    for path, text in files.items():
        path.write_text(text)
    print(f"wrote {len(files)} files to {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
